enum Book {
  genesis(title: 'Genesis', chapterCount: 50),
  exodus(title: 'Exodus', chapterCount: 40),
  leviticus(title: 'Leviticus', chapterCount: 27),
  numbers(title: 'Numbers', chapterCount: 36),
  deuteronomy(title: 'Deuteronomy', chapterCount: 34),
  joshua(title: 'Joshua', chapterCount: 24),
  judges(title: 'Judges', chapterCount: 21),
  ruth(title: 'Ruth', chapterCount: 4),
  firstSamuel(title: '1 Samuel', chapterCount: 31),
  secondSamuel(title: '2 Samuel', chapterCount: 24),
  firstKings(title: '1 Kings', chapterCount: 22),
  secondKings(title: '2 Kings', chapterCount: 25),
  firstChronicles(title: '1 Chronicles', chapterCount: 29),
  secondChronicles(title: '2 Chronicles', chapterCount: 36),
  ezra(title: 'Ezra', chapterCount: 10),
  nehemiah(title: 'Nehemiah', chapterCount: 13),
  esther(title: 'Esther', chapterCount: 10),
  job(title: 'Job', chapterCount: 42),
  psalms(title: 'Psalms', chapterCount: 150),
  proverbs(title: 'Proverbs', chapterCount: 31),
  ecclesiastes(title: 'Ecclesiastes', chapterCount: 12),
  songOfSongs(title: 'Song of Songs', chapterCount: 8),
  isaiah(title: 'Isaiah', chapterCount: 66),
  jeremiah(title: 'Jeremiah', chapterCount: 52),
  lamentations(title: 'Lamentations', chapterCount: 5),
  ezekiel(title: 'Ezekiel', chapterCount: 48),
  daniel(title: 'Daniel', chapterCount: 12),
  hosea(title: 'Hosea', chapterCount: 14),
  joel(title: 'Joel', chapterCount: 3),
  amos(title: 'Amos', chapterCount: 9),
  obadiah(title: 'Obadiah', chapterCount: 1),
  jonah(title: 'Jonah', chapterCount: 4),
  micah(title: 'Micah', chapterCount: 7),
  nahum(title: 'Nahum', chapterCount: 3),
  habakkuk(title: 'Habakkuk', chapterCount: 3),
  zephaniah(title: 'Zephaniah', chapterCount: 3),
  haggai(title: 'Haggai', chapterCount: 2),
  zechariah(title: 'Zechariah', chapterCount: 14),
  malachi(title: 'Malachi', chapterCount: 4),
  matthew(title: 'Matthew', chapterCount: 28),
  mark(title: 'Mark', chapterCount: 16),
  luke(title: 'Luke', chapterCount: 24),
  john(title: 'John', chapterCount: 21),
  acts(title: 'Acts', chapterCount: 28),
  romans(title: 'Romans', chapterCount: 16),
  firstCorinthians(title: '1 Corinthians', chapterCount: 16),
  secondCorinthians(title: '2 Corinthians', chapterCount: 13),
  galatians(title: 'Galatians', chapterCount: 6),
  ephesians(title: 'Ephesians', chapterCount: 6),
  philippians(title: 'Philippians', chapterCount: 4),
  colossians(title: 'Colossians', chapterCount: 4),
  firstThessalonians(title: '1 Thessalonians', chapterCount: 5),
  secondThessalonians(title: '2 Thessalonians', chapterCount: 3),
  firstTimothy(title: '1 Timothy', chapterCount: 6),
  secondTimothy(title: '2 Timothy', chapterCount: 4),
  titus(title: 'Titus', chapterCount: 3),
  philemon(title: 'Philemon', chapterCount: 1),
  hebrews(title: 'Hebrews', chapterCount: 13),
  james(title: 'James', chapterCount: 5),
  firstPeter(title: '1 Peter', chapterCount: 5),
  secondPeter(title: '2 Peter', chapterCount: 3),
  firstJohn(title: '1 John', chapterCount: 5),
  secondJohn(title: '2 John', chapterCount: 1),
  thirdJohn(title: '3 John', chapterCount: 1),
  jude(title: 'Jude', chapterCount: 1),
  revelation(title: 'Revelation', chapterCount: 22);

  const Book({required this.title, required this.chapterCount});

  final String title;
  final int chapterCount;
}
